---
title: "STD Daten 2020"
author: "Bernard Surial"
date: "`r format(lubridate::today(), '%d. %B %Y')`"
output:
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      dpi = 300)
```

# Chlamydien

```{r chlam}
readd(ct_plot_cases)

readd(ct_plot_incidence)

readd(ct_plot_cases_sex)
```



# Gonokokken

```{r gono}
readd(ngo_plot_cases)

readd(ngo_plot_incidence)

readd(ngo_plot_cases_sex)
```



# HIV

```{r hiv}
readd(hiv_plot_cases)

readd(hiv_plot_incidence)

readd(hiv_plot_cases_sex)
```



# Syphilis

```{r syph}
readd(syph_plot_cases)

readd(syph_plot_incidence)

readd(syph_plot_cases_sex)
```




# Daten der Anonymen Teststelle

```{r teststelle}
readd(berda_graph_visits)

readd(berda_graph_tests)

readd(berda_graph_cases)
```


```{r teststelle2, fig.width=10}
readd(pos_chlam)

readd(pos_gono)
```




# Daten vom IFIK

```{r ifik-CT, fig.height=8}
readd(ifik_ct_plot)
```

```{r ifik-NGO, fig.height=8}
readd(ifik_ngo_plot)
```


```{r}
readd(ifik_ct_year_cases_plot)
readd(ifik_ct_year_rate_plot)
```


```{r}
readd(ifik_ngo_year_cases_plot)
readd(ifik_ngo_year_rate_plot)
```

