---
title: "STD Daten 2020"
author: "Bernard Surial"
date: "`r format(lubridate::today(), '%d. %B %Y')`"
output:
  html_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      dpi = 300)

library(tidyverse)
library(here)

source(here("scripts", "01-bag_HIV.R"))
source(here("scripts", "02-bag_CT.R"))
source(here("scripts", "03-bag_NGO.R"))
source(here("scripts", "04-bag_syphilis.R"))

theme_set(theme_light(base_family = "Roboto") + 
            theme(panel.grid.minor.x = element_blank(),
                  plot.title.position = "panel", 
                  plot.title = element_text(face = "bold"),
                  plot.caption = element_text(face = "italic")))

```

```{r}
# Cases graph
cases_graph <- function(df, text_distance = -750) {
  df %>%
    mutate(
      pct_change = (value - lag(value)) / lag(value)
    ) %>%
    mutate(pct_change_ft = scales::percent(pct_change, accuracy = 0.1)) %>% 
    ggplot(aes(x = year, y = value)) +
    geom_text(aes(
      label = pct_change_ft, y = value + text_distance,
      color = pct_change >= 0
    ),
    family = "Roboto", size = 3, show.legend = FALSE
    ) +
    geom_line(aes(group = 1)) +
    geom_point(aes(color = pct_change >= 0),
               show.legend = FALSE,
               size = 2
    ) +
    expand_limits(y = 0) +
    scale_color_manual(values = c("firebrick", "darkgreen")) +
    scale_x_continuous(
      breaks = seq(2010, 2020, 1),
      labels = scales::comma_format(
        accuracy = 1,
        big.mark = ""
      )
    ) +
    scale_y_continuous(labels = scales::comma_format(big.mark = "'")) + 
    labs(x = "\nCalendar year", 
       caption = "Source: Bundesamt für Gesundheit")
}
```

```{r}
# cases_sex_graph
cases_sex_graph <- function(df, text_distance) {
df %>% 
  select(-c(std, metric)) %>% 
  pivot_longer(-year) %>%
  mutate(value = as.numeric(value)) %>% 
  filter(name != "unbekannt") %>% 
  arrange(name, year) %>% 
  group_by(name) %>% 
  mutate(pct_change = (value - lag(value)) / lag(value)) %>%
  mutate(pct_change_ft = scales::percent(pct_change, accuracy = 0.1)) %>% 
  ggplot(aes(x = year, y = value)) + 
  geom_line(aes(linetype = name, group = name)) +
  geom_text(aes(label = pct_change_ft, color = pct_change >= 0, 
                y = value + text_distance),
          family = "Roboto", size = 3, show.legend = FALSE) +
  geom_point(aes(color = pct_change >= 0), 
             size = 2, show.legend = FALSE) +
  expand_limits(y = 0)  + 
  scale_color_manual(values = c("firebrick", "darkgreen")) + 
  labs(linetype = "Gender", x = "\nCalendar year", 
       caption = "Source: Bundesamt für Gesundheit")
}
```


# Chlamydien

```{r}
cases_ct <- cases_ct %>% 
  select(1:2) %>% 
  mutate(value = as.numeric(value))

cases_ct %>%
  cases_graph() + 
  labs(
    y = "No. of new C. trachomatis cases",
    title = "CH: Number of C. trachomatis cases"
  )
```

```{r}
cases_sex_graph(cases_sex_ct, 300) + 
  labs(y = "No. of new C. trachomatis cases\n", 
       title = "CH: Number of C. trachomatis cases (by gender)") 
```


```{r}
incidence_ct %>% 
  mutate(value = as.numeric(value)) %>% 
  cases_graph(5) + 
  labs(y = "Inzidenz pro 100'000 Einwohner\n", 
       title = "CH: Incidence of new C. trachomatis cases, per 100'000")
```



# Gonokokken

```{r}
cases_ngo %>% 
  mutate(value = as.numeric(value)) %>% 
  cases_graph(text_distance = -200) +
  labs(
    y = "No. of new N. gonorhoeae cases\n",
    title = "CH: Number of N. gonorrhoeae cases")
```

```{r}
cases_sex_graph(cases_sex_ngo, 200) + 
    labs(y = "No. of new N. gonorrhoeae cases\n",
    title = "CH: Number of N. gonorrhoeae cases (by gender)"
  ) 
```


```{r}
incidence_ngo %>% 
  mutate(value = as.numeric(value)) %>% 
  cases_graph(2) + 
  labs(y = "Inzidenz pro 100'000 Einwohner\n", 
       title = "CH: Incidence of new N. gonorrhoeae cases, per 100'000")
```


# HIV

```{r}
cases_hiv %>% 
  mutate(value = as.numeric(value)) %>% 
  cases_graph(text_distance = -15) + 
  labs(x = "\nCalendar Year", y = "No. of new HIV cases\n",
    title = "CH: Number of new HIV cases",
    caption = "Source: Bundesamt für Gesundheit")
```

```{r}
cases_sex_hiv %>% 
  cases_sex_graph(-5) + 
  labs(y = "No. of new HIV cases\n", 
       title = "CH: Number of new HIV cases (by gender)")
```

```{r}
incidence_hiv %>% 
  mutate(value = as.numeric(value)) %>% 
  cases_graph(0.2) + 
  labs(y = "Inzidenz pro 100'000 Einwohner\n", 
       title = "CH: Incidence of new HIV cases, per 100'000")
```
